
# formula_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x9d\xed\x16\xa4\xf2<\xd3\x98\\a\xfd\xa3\x12\x9a\xc0\xc6'

_lr_action_items = {'TERM':([0,6,11,12,15,16,],[1,1,1,1,1,1,]),'IDENT':([0,6,10,11,12,15,16,],[2,2,2,2,2,2,2,]),'RPAREN':([2,4,5,8,13,14,17,18,21,22,23,24,25,],[-4,-5,-9,-8,-11,21,24,25,-10,-6,-7,-12,-13,]),'QUOTED':([0,6,10,11,12,15,16,],[4,4,4,4,4,4,4,]),'EQUALS':([2,3,4,],[-4,12,-5,]),'ONE':([0,6,11,12,15,16,],[8,8,8,8,8,8,]),'ZERO':([0,6,11,12,15,16,],[5,5,5,5,5,5,]),'PLUS':([2,3,4,5,8,9,13,14,19,20,21,22,23,24,25,],[-4,-11,-5,-9,-8,15,-11,15,15,15,-10,-6,-7,-12,-13,]),'LPAREN':([0,1,6,11,12,15,16,],[6,10,6,6,6,6,6,]),'DISTRIB':([2,3,4,],[-4,11,-5,]),'TIMES':([2,3,4,5,8,9,10,13,14,19,20,21,22,23,24,25,],[-4,-11,-5,-9,-8,16,18,-11,16,16,16,-10,16,-7,-12,-13,]),'$end':([2,3,4,5,7,8,9,13,19,20,21,22,23,24,25,],[-4,-11,-5,-9,0,-8,-3,-11,-2,-1,-10,-6,-7,-12,-13,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,],[7,]),'expression':([0,6,11,12,15,16,],[9,14,19,20,22,23,]),'name':([0,6,10,11,12,15,16,],[3,13,17,13,13,13,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> name EQUALS expression','formula',3,'p_formula','formula.py',570),
  ('formula -> name DISTRIB expression','formula',3,'p_formula','formula.py',571),
  ('formula -> expression','formula',1,'p_formula2','formula.py',577),
  ('name -> IDENT','name',1,'p_name','formula.py',583),
  ('name -> QUOTED','name',1,'p_name','formula.py',584),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','formula.py',590),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','formula.py',591),
  ('expression -> ONE','expression',1,'p_expression_one','formula.py',598),
  ('expression -> ZERO','expression',1,'p_expression_zero','formula.py',604),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_paren','formula.py',610),
  ('expression -> name','expression',1,'p_expression_var','formula.py',616),
  ('expression -> TERM LPAREN name RPAREN','expression',4,'p_expression_func','formula.py',622),
  ('expression -> TERM LPAREN TIMES RPAREN','expression',4,'p_expression_func','formula.py',623),
]
